# NumPy

Fast numerical computing with N-dimensional arrays.

**In this notebook:**
- Arrays, dtypes, and creation functions
- Indexing and slicing
- Vectorised operations
- Broadcasting
- Shape manipulation
- Aggregations
- Linear algebra

## 1. Arrays, dtypes, and creation

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
m = np.array([[1, 2, 3], [4, 5, 6]])

print('Shape:', m.shape)    # (2, 3)
print('dtype:', m.dtype)    # int64
print('ndim:', m.ndim)      # 2
print('size:', m.size)      # 6

# Creation helpers
print(np.zeros((3, 3)))
print(np.eye(4))
print(np.arange(0, 10, 2))        # [0 2 4 6 8]
print(np.linspace(0, 1, 5))       # [0.   0.25 0.5  0.75 1.  ]
print(np.random.randint(0, 10, (3, 3)))

## 2. Indexing and Slicing

In [ ]:
a = np.array([10, 20, 30, 40, 50])
print(a[0], a[-1])    # 10 50
print(a[1:4])         # [20 30 40]
print(a[::2])         # [10 30 50]

m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m[1, 2])        # 6
print(m[:, 1])        # [2 5 8] — column 1
print(m[1:, :2])      # [[4 5], [7 8]]

# Boolean indexing
print(a[a > 25])            # [30 40 50]
print(a[a % 2 == 0])        # [20 40]

# Modify in place
a[a < 20] = 0
print(a)                    # [ 0 20 30 40 50]

## 3. Vectorised Operations

Operations apply element-wise — no Python loops needed. This is 10–100× faster than equivalent list comprehensions.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a + b)       # [11 22 33 44 55]
print(a * b)       # [ 10  40  90 160 250]
print(a ** 2)      # [ 1  4  9 16 25]
print(np.sqrt(a))  # [1.    1.414 1.732 2.    2.236]
print(np.dot(a, b))   # 550 — dot product
print(a @ b)          # same

## 4. Broadcasting

NumPy stretches smaller arrays to match the shape of larger ones. **Rule:** dimensions are compatible when equal or one is 1.

In [ ]:
m = np.array([[1, 2, 3], [4, 5, 6]])   # shape (2, 3)

row = np.array([10, 20, 30])    # shape (3,) → adds to every row
print(m + row)
# [[11 22 33]
#  [14 25 36]]

col = np.array([[100], [200]])  # shape (2, 1) → adds to every column
print(m + col)
# [[101 102 103]
#  [204 205 206]]

# Zero-centre columns in one line
print(m - m.mean(axis=0))    # each col has mean 0

## 5. Shape Manipulation

In [ ]:
a = np.arange(12)
print(a.reshape(3, 4))        # 3 rows, 4 cols
print(a.reshape(2, 2, 3))     # 3-D tensor

m = a.reshape(3, 4)
print(m.flatten())             # copy → 1-D
print(m.T)                     # transpose, shape (4, 3)

# Stack and split
x = np.arange(4)
y = np.arange(4, 8)
print(np.vstack([x, y]))       # shape (2, 4)
print(np.hstack([x, y]))       # shape (8,)
print(np.split(np.arange(6), 3))   # [array([0,1]), array([2,3]), array([4,5])]

## 6. Aggregations

In [ ]:
m = np.array([[1, 2, 3], [4, 5, 6]])

print(m.sum())           # 21
print(m.sum(axis=0))     # [5 7 9]  — column sums
print(m.sum(axis=1))     # [6 15]   — row sums
print(m.mean())          # 3.5
print(m.std())           # 1.707...
print(m.min(), m.max())  # 1 6
print(m.argmax())        # 5 — flat index of max

# Sorting
data = np.array([5, 2, 8, 1, 9, 3])
print(np.sort(data))           # [1 2 3 5 8 9]
print(np.argsort(data))        # [3 1 5 0 2 4]
print(np.where(data > 5, 1, 0)) # [0 0 1 0 1 0]

## 7. Linear Algebra

In [ ]:
A = np.array([[2., 3.], [5., -1.]])
b = np.array([8., -2.])

# Solve Ax = b
x = np.linalg.solve(A, b)
print(f'Solution: x={x[0]:.4f}, y={x[1]:.4f}')
print('Verify:', np.allclose(A @ x, b))   # True

print('Determinant:', np.linalg.det(A))
print('Inverse:\n', np.linalg.inv(A))

# Eigenvalues
C = np.array([[4., 2.], [1., 3.]])
vals, vecs = np.linalg.eig(C)
print('Eigenvalues:', vals)

## Practice

| File | Difficulty | Topics |
|---|---|---|
| [01-easy.py](exercises/01-easy.py) | Easy | Array creation, indexing, vectorised ops |
| [02-medium.py](exercises/02-medium.py) | Medium | Broadcasting, reshape, aggregations |
| [03-challenge.py](exercises/03-challenge.py) | Challenge | Linear algebra, statistics, performance |

Solutions: [solutions/](solutions/)